module.exports = {
  admin: {
    authNotRequire: [
      "/accountLogin",
      "/verify/otp",
      "/resend/otp",
      "/forgot/password",
      "/password/generate",
      "/user/userdetail",
      "/verifyotp",
      "/forgot/password/otp",
      "/testOrigin",
      "/dashboard/workallocations",
      "/current/version",
      "/dashboard/list/employee",
      "/user/forgot/password",
      "/user/verify/token",
    ], // admin mush validate authorization require for this end points then only they can process
    language: [],
  },
  user: {
    authNotRequire: [
      "/home",
      "/accountLogin",
      "/mobileNo/login",
      "/verify/otp",
      "/resend/otp",
      "/create",
      "/forgot/password",
      "/password/generate",
      "/verifyotp",
      "/userdetail",
      "/chat",
      "/chat/1",
      "/chat/message",
      "/checkuserpresent",
      "/checkuserpresentverifyotp",
      "/mobileNo/verify",
      "/mobileNo/otp/verify",
      "/upload/file",
      "/vehicle/types/list",
      "/vehicle/category/list",
      "testOrigin",
      "/mobile/login",
      "/current/version",
    ],
    language: [],
  },
  index: {
    authNotRequire: ["/", "/config/aws"],
    language: [],
  },
};
