module.exports = {
  permission: [
    {
      label: "User",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "reset", enable: true },
        { label: "export", enable: true },
        { label: "query", enable: true },
        // { label: "allDownload", enable: true },
        { label: "import", enable: true },
        { label: "uploadhistory", enable: true },
        // { label: "sendemail", enable: true },
      ],
    },
    {
      label: "Role",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        // { label: "assign", enable: true },
        { label: "query", enable: true },
        // { label: "export", enable: true },
      ],
    },
    {
      label: "Organization",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "Invoice",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "duplicate", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "Payment",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },
    // {
    //   label: "EmailTemplate",
    //   enable: true,
    //   isParent: true,
    //   buttons: [
    //     // { label: "add", enable: true },
    //     { label: "edit", enable: true },
    //     { label: "delete", enable: true },
    //     { label: "query", enable: true },
    //     { label: "export", enable: true },
    //     { label: "triggeremail", enable: true },
    //   ],
    // },
    {
      label: "Clients",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
        { label: "import", enable: true },
        { label: "uploadhistory", enable: true },
      ],
    },
    {
      label: "Quote",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "duplicate", enable: true },
        { label: "export", enable: true },
      ],
    },

    {
      label: "Event",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },

    {
      label: "EmployeeProfile",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "query", enable: true },
      ],
    },

    {
      label: "TeamManagement",
      enable: true,
      isParent: true,
      buttons: [
        // { label: "add", enable: true },
        // { label: "edit", enable: true },
        // { label: "delete", enable: true },
        { label: "export", enable: true },
        { label: "query", enable: true },
      ],
    },

    {
      label: "ProjectsSummary",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
      ],
    },

    {
      label: "PendingApprovals",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
      ],
    },

    {
      label: "TaskAndActivity",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
      ],
    },
    {
      label: "ResourceManagement",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },

    {
      label: "PrivacyPolicies",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },

    {
      label: "PO",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "duplicate", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "COR",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "duplicate", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "Projects",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "view", enable: true },
        { label: "export", enable: true },
        { label: "allocation", enable: true },
      ],
    },
    {
      label: "Activity",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "appliedUser", enable: true },
        { label: "export", enable: true },
        { label: "query", enable: true },
      ],
    },
    {
      label: "Department",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "export", enable: true },
        { label: "query", enable: true },
      ],
    },
    {
      label: "workallocation",
      enable: true,
      isParent: true,
      buttons: [
        // { label: "add", enable: true },//we are using allocation instead of add
        { label: "edit", enable: true },
        { label: "view", enable: true },
        { label: "delete", enable: true },
        { label: "export", enable: true },
        { label: "query", enable: true },
        { label: "allocation", enable: true },
      ],
    },

    {
      label: "Rating",
      enable: true,
      isParent: false,
      buttons: [
        { label: "add", enable: true },
        { label: "view", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },

    {
      label: "Appreciation",
      enable: true,
      isParent: false,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "view", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
        // { label: "comment", enable: true },
      ],
    },
    {
      label: "Timesheet",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "view", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "LeaveRequests",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        // { label: "view", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "ExpenseClaim",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        // { label: "view", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "Setting",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "Dashboard",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "view", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },

    {
      label: "Notification",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "Chat",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },
    {
      label: "Ticketing",
      enable: true,
      isParent: true,
      buttons: [
        { label: "add", enable: true },
        { label: "edit", enable: true },
        { label: "delete", enable: true },
        { label: "query", enable: true },
        { label: "export", enable: true },
      ],
    },
  ],
};
